name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        #with:
        #  submodules: recursive
      - run: sudo apt install -y llvm-11 clang-11
      - run: sudo ln -s /usr/bin/llvm-config-11 /usr/bin/llvm-config
      - run: make -j$(nproc)
      - uses: actions/upload-artifact@v2
        with:
          name: adscript
          path: build/adscript
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: adscript
          path: build/artifact
      - run: sudo apt install tree
      - run: tree
      #- run: adscript test/basic.adscript
      #- run: clang test/main.c test/basic.o -o test/test.out
      #- run: test/test.out

