name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        #with:
        #  submodules: recursive
      - run: sudo apt install -y llvm-11 clang-11
      - run: sudo ln -s /usr/bin/llvm-config-11 /usr/bin/llvm-config
      - run: make -j$(nproc) test
      - uses: actions/upload-artifact@v2
        with:
          name: adscript
          path: build/adscript
