name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        #with:
        #  submodules: recursive
      - run: sudo apt install -y llvm-12 clang-12
      - run: sudo ln -s /usr/bin/llvm-config-12 /usr/bin/llvm-config
      - name: build
        run: make -j$(nproc)
      - name: test
        run: make -j$(nproc) test
      - uses: actions/upload-artifact@v2
        with:
          name: adscript
          path: adscript
